//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFullTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.DailySummaries = new HashSet<DailySummary>();
        }
    
        public string WbanId { get; set; }
        public string WMO { get; set; }
        public string CallSign { get; set; }
        public string ClimateDivisionCode { get; set; }
        public string ClimateDivisionStateCode { get; set; }
        public string ClimateDivisionStationCode { get; set; }
        public string StationName { get; set; }
        public string StationState { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> GroundHeight { get; set; }
        public Nullable<decimal> StationHeight { get; set; }
        public Nullable<decimal> Barometer { get; set; }
        public Nullable<decimal> TimeZone { get; set; }
        public string PrimarySite { get; set; }
        public string SiteHasData { get; set; }
    
        public virtual ICollection<DailySummary> DailySummaries { get; set; }
    }
}
