//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFullTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_DailySummaryUniqueWbans
    {
        public string WbanId { get; set; }
    }
}
