//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySummary
    {
        public string WbanId { get; set; }
        public System.DateTime YearMonthDayId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public Nullable<decimal> TempMax { get; set; }
        public Nullable<decimal> TempMin { get; set; }
        public Nullable<decimal> TempAvg { get; set; }
        public Nullable<decimal> Water1 { get; set; }
        public Nullable<decimal> SnowFall { get; set; }
        public Nullable<decimal> PrecipTotal { get; set; }
        public Nullable<decimal> WindAvgSpeed { get; set; }
        public Nullable<decimal> WindMax5Speed { get; set; }
        public Nullable<decimal> WindMax2Speed { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
